### ISSUE TITLE
Create em api

### ISSUE THREAD

**Issue by dehvmartins** [guru-ce/forum#11]
Tenho uma API que usa active model serializer. Reparei que muita gente usa o padrão

```
def create
   render json: Model.create(model_params)
end
```

Mas nos casos de parametros invalidos, não muda o status nem mostra os erros, ao inves disso só retorna o objeto com os valores nulos. O mais recomendado  seria seguir o caminho do if/else ou tem outro comando mais direto?

**Comment by filipebarcos** [comment]
@dehvmartins eu uso o esquema do if/else.

2 motivos, Status code e Payload.

Quando o seu create é válido, vc vai querer retornar o objeto criado e um status `201`. 

``` ruby
render json: created_model, status: :created
```

 Se falhar, vc quer retornar os erros, e um status code, como o `422`.
Para mostrar os erros é legal tratar o `model.errors`, pra vc conseguir colocar ele de forma bonita e de acordo com o esquema de payload da tua API, eu custo ter um método no meu application controller que faz isso. O controller ficaria mais ou menos assim (supondo o exemplo `user has many credit cards`)

``` ruby
def create
  credit_card = current_user.credit_cards.build(create_params)
  if credit_card.save
    render json: credit_card, status: :created
  else
    render json: to_errors(credit_card.errors), status: :unprocessable_entity
  end
end
```

**Comment by rafaelsales** [comment]
`respond_with Model.create(model_params)` ftw

**Comment by rafaelsales** [comment]
E se vc quiser customizar o respond_with, vc pode fazer API-wide, implementando o seu próprio `ActionController::Responder` e setando sua implementação no seu base-api-controller

**Comment by dehvmartins** [comment]
@filipebarcos bacana, eu fui por esse caminho mesmo, mas usei o error serializer do próprio ams por enquanto.
`status: :unprocessable_entity, adapter: :json_api, serializer: ActiveModel::Serializer::ErrorSerializer`
@rafaelsales um bom do respond_with é que serve tanto para API como para view ;)

**Comment by rafaelsales** [comment]
Então, na app que estou trabalhando, o Rails é só API, então usamos respond_with só pra API mesmo, e a grande vantagem é que 95% de todas as nossas actions tem somente uma linha com `respond_with resource.do_something` e aí como falei, se vc não está satisfeito com os status codes e handling to respond_with, vc pode customizar ele e aí se aplica à API inteira. Foi a melhor solução que encontramos pra reduzir boilerplate na API e escalar com um padrão mais facilmente.
