### ISSUE TITLE
Executar determinada ação baseada em uma data

### ISSUE THREAD

**Issue by victorsilent** [guru-ce/forum#12]
Olar :p
Indo um pouco direto ao ponto, eu possuo uma model, Conta, e essa model possui um atributo saldo e também possui vários Lançamentos, quando crio um lançamento, eu posso adicionar uma data e um valor de crédito ou débito que será acionado para aquela determinada conta no dia X cadastrado. A minha dúvida é: Onde eu poderia colocar o método para executar todos os debitos/creditos daquele dia? Eu fiquei em dúvida porque ao colocar ele na model da Conta, (e executar a cada 24h?) me pareceu um pouco estranho, queria saber se teria uma solução melhor para isso :p

**Comment by herminiotorres** [comment]
Então eu acho que você tem que ter um model de lançamentos, e lá você diz se vai ser debito ou credito, valor e conta de oridem e destino.

Daí você usa esse cara aqui [Clockwork - a clock process to replace cron](https://github.com/tomykaira/clockwork) e você diz a data que ele vai rodar essa operação de lançamento e só! Dai ele vai pegar o id do lançamento e vai rodar todos que tiver naquela data!

**Comment by victorsilent** [comment]
A model de lançamentos eu tenho, foi falha minha não ter colocado ali.
Dei uma olhada rapida na gem, achei massa! Vlws @herminiotorres

**Comment by filipebarcos** [comment]
Acho que são duas perguntas que vc tem aqui. 

1) Como executar uma tarefa recorrente?
2) Onde colocar a lógica para executar os lançamentos?

Para a pergunta 1, o Hermínio deu uma boa dica, mas lembre-se que é importante monitorar o processo, não acho que o Clockwork reinicie o processo automaticamente, caso ele morra (Se seu app tiver no Heroku, isso não vai ser um problema)

Para a pergunta dois, existem VÁRIAS respostas. O que eu faria, é ter um PORO (que funcionaria como um Service ou business object, seja lá como vc queira chamar), chamado `Calculadora` (já que seu app parece estar em português) que receba a conta e faça os cálculos necessários (eu teria um model para log dessas atualizações de saldo da conta, acho que é importante saber como e pq o estado desse model mudou, mas isso é outros 500).

``` ruby
# ou apenas `saldo` se vc não quiser mudar o estado, 
# e sim retornar um valor novo
Calculadora.new(conta).atualiza_saldo 
```

**Comment by thmzlt** [comment]
O Clockwork é show de bola, mas ele vai levantar outro processo com a sua app carregada na memória o que pode inviabilizar o seu servidor. Um cron job (que chama uma Rake task) acaba sendo mais econômico, e se tiver no Heroku tem o [scheduler](https://elements.heroku.com/addons/scheduler) que faz a mesma coisa.

**Comment by victorsilent** [comment]
Consegui rodar no heroku com o Clockwork, deu tudo certinho mesmo.
Com o clock rodando, para cada "Account" ativa ele pegasse todos os docs dela e caso aquele doc fosse para o dia de hoje ele iria chamar o metodo update_account e passar o valor desse doc.

Agora um ponto que eu fiquei em duvida quando estava fazendo, essa é uma abordagem, minimamente, correta? 
Tipo, suponha um site tipo esse: http://cc.welancer.com/projeto-detalhe.aspx?pid=9040
Nesse caso ai eles tem algo parecido, a cada dia que passa eles vão decrementando ali na contagem dos dias e isso altera o estado do projeto. Porem, eles tem uma quantidade grande de projetos, se eu usasse essa mesma abordagem dentro da plataforma deles talvez ela ficasse muito lenta durante o processamento... 
Existiria uma outra maneira de fazer isso? Sempre fico pensando em formas de quebrar o que eu fiz e acredito que essa seja uma dessas formas :p

**Comment by filipebarcos** [comment]
usar o clockwork ou não, não é a questão, mas a implementação, no caso da sua pergunta (se é que eu entendi direito).

Se percorrer cada conta é algo custoso, divida para conquistar. Outra coisa que é importante pensar é, se o update de uma das contas falhar, todos devem falhar? Deve continuar? O que acontece no seu caso? Se vc tiver que rodar novamente o código, em caso de falha, os que foram atualizados com sucesso serão atualizados novamente, ou ignorados (traduzindo: seu código é idempotente)?

Acho que essas são questões mais válidas para o caso.
