### ISSUE TITLE
Devise. Como fazer login ao fazer signup mas continuar enviando e-mail de confirmação?

### ISSUE THREAD

**Issue by renatosousafilho** [guru-ce/forum#13]
Pessoal, estou desenvolvendo aqui a parte de login de uma app mas estou com a seguinte dificuldade.

Precisei habilitar que ao usuário realizar o signup (cadastro) ele já se logue automaticamente mas ainda ficará pendente de completar algumas informações de seu cadastro para ter acesso a algumas features. Para isso fiz desta forma.

```
class User < ActiveRecord::Base
 protected
  def confirmation_required?
    false
  end
end
```

Isto funcionou e resolveu parte do problema, agora eu posso efetuar o login. Porém o e-mail de confirmação não está sendo enviado por que até onde entendi ao definir que a confirmação não é mais requerida ele além de de permitir esse login sem confirmação, omite o envio do disparo de confirmação. Mas caso o usuário reenvie as instrunções de confirmação acontece normalmente.

Alguém pode me dar uma ideia de como resolver isso por que preciso que este email seja enviado ao fazer esse signup.

**Comment by thmzlt** [comment]
Para decidir se deve ou não enviar o email de confirmação, o Devise chama no seu `User` o método `#send_confirmation_notification?`, e esse método retorna `true` se o `#confirmation_required?` também retornar `true`, como diz [aqui](https://github.com/plataformatec/devise/blob/ac702843ddaa5652fde7a0050ff2378e7368149e/lib/devise/models/confirmable.rb#L276-L278).

Então eu imagino que o seu problema vai ser resolvido se você também override o `#send_confirmation_notification?`. Por exemplo:

``` ruby
class User < ActiveRecord::Base
  def confirmation_required?
    false
  end

  def send_confirmation_notification?
    !@skip_confirmation_notification && self.email.present?
  end
end

```

**Comment by renatosousafilho** [comment]
@thmzlt , eu chequei aqui e a soluçao e ela funcionou porém encontrei um outro problema. Estou usando DeviseAsync  para jogar o processamento do envio de e-mail em uma instancia do Sidekiq. Não sei por que razão mas ao fazer isso ele está disparando dois e-mails. Uma das instrunções de confirmação de cadastro e um outro informando que a senha foi alterada.

Testei desabilitar o DeviseAsync e ele dispara apenas o e-mail de confirmação. Tem uma ideia do que pode estar acontecendo?

Esta é a gem que estou utilizando.
https://github.com/mhfs/devise-async

**Comment by thmzlt** [comment]
Não sei, mas se você olhar no [source do devise-async](https://github.com/mhfs/devise-async/blob/master/lib/devise/async/model.rb#L23-L45) dá pra ver que ele overwrite um método do Devise. Deve estar aí o seu problema.

**Comment by renatosousafilho** [comment]
@thmzlt pois é, tava checando aqui e por alguma razão ele ta passando uma flag indicando que a senha foi alterada mesmo que eu esteja apenas cadastrando o usuário. Estou fazendo apenas um User.create mas ainda assim essa flag está sendo passada. To tentando descobrir em que momento é chamado essa calback e por que ele está passando isso como parametro.
