### ISSUE TITLE
Watch file

### ISSUE THREAD

**Issue by evaldosantos** [guru-ce/forum#14]
Oi pessoal, boa tarde.

Estou com o seguinte problema: preciso verficar alteracoes em um arquivo da minha app, e caso o arquivo seja alterado, uma rotina eh disparada. Tentei fazer isso usando a gem guard/listen. 

Configurei o "listen" em config/application.rb para iniciar o listen quando a aplicação é iniciada.

Em modo dev (webrick) roda tudo de boa. No entanto quando rodo em produção (unicorn/nginx), apesar do listen iniciar, as alterações não são disparadas.

Alguém poderia me dar uma ajuda com isso, ou sugerir uma forma melhor de como fazer esse processo?

**Comment by fernandodev** [comment]
1. https://mmonit.com/monit/
2. tu pode criar uma rake task pra isso

**Comment by evaldosantos** [comment]
Vi o lance do monit, mas não consegui usar. Acabei criando uma rake task, e até agora ta ok.
