### ISSUE TITLE
Próximo encontro?

### ISSUE THREAD

**Issue by franzejr** [guru-ce/forum#3]
Novidades de quando será?

**Comment by Viniciuscarvalho** [comment]
@franzejr Ninguém disse uma data para realização do evento e ficou por isso mesmo. Preciso que me digam data, sendo terça-feira para conseguir falar com o gerente do Boozers.

**Comment by filipebarcos** [comment]
Começamos a discutir agora mesmo no canal `proximo-encontro` no slack.
