### ISSUE TITLE
Documentação de API

### ISSUE THREAD

**Issue by dehvmartins** [guru-ce/forum#5]
Pessoal, o que vocês usam(se usam) ou acham bacana, para documentação de API?

**Comment by filipebarcos** [comment]
Acho que o melhor que tem por aí é [API Blueprint](https://apiblueprint.org/) + [Apiary](https://apiary.io/). E se vc quiser testar e garantir que a sua API fica atualizada, pode incluir o `dredd` (pacote que fica no npm) pra testar.

Com o Apiary, ainda fica tudo interativo e bonitinho 😄

**Comment by herminiotorres** [comment]
Achei essa lista:
- [swagger](http://swagger.io)
- [apipie](https://github.com/Apipie/apipie-rails)
- [apitome](https://github.com/modeset/apitome)
- [slate](https://github.com/lord/slate)
- [api-blueprint](https://github.com/apiaryio/api-blueprint)
- [calamum](https://github.com/malachheb/calamum)

Porém, não cheguei a utilizar nenhuma dessas ferramentas para Documentação de API.

**Comment by fernandodev** [comment]
Eu uso do [apipie](https://github.com/Apipie/apipie-rails). É legalzinho, mas tem outros mais bacanas..

**Comment by fernandodev** [comment]
@dehvmartins olha esse aqui: http://sabisu.herokuapp.com/sabisu_rails/explorer

live http://sabisu.herokuapp.com/sabisu_rails/explorer

```
user: admin
pwd: sekret
```
