### ISSUE TITLE
Dois Apps, um só database

### ISSUE THREAD

**Issue by dehvmartins** [guru-ce/forum#6]
Bem, eu estou com dois apps que compartilham o mesmo banco. cada app tem migrations diferentes e um usa o banco do outro. A nível de desenvolvimento e heroku tudo funciona.

O problema é o seguinte: como configurar isso no CI? Porque localmente eu aponto para o banco certo e funciona. Estou usando o wercker mas se você tiver alguma ideia de como fazer isso no circleci ou qualquer outro já ajuda.

**Comment by fernandodev** [comment]
Tu podes fazer assim:

```
## Customize database setup
database:
  override:
    # replace CircleCI's generated database.yml
    - cp config/database.yml.ci config/database.yml
    - bundle exec rake db:create db:schema:load
```

https://circleci.com/docs/config-sample/

Não sei isso te responde.

**Comment by dehvmartins** [comment]
@fernandodev mas com isso o banco só vai ter as tabelas de um app

**Comment by fernandodev** [comment]
Entendo, nesse caso. Tu pode apontar pra um database no heroku.

Tipo, cria o app 1 e 2 com environment em test no heroku e usa o mesmo database pro circle ci
