### ISSUE TITLE
has_many :through ou has_and_belongs_to_many?

### ISSUE THREAD

**Issue by DenysonDomingos** [guru-ce/forum#7]
Boa noite pessoal. Primaria essa duvida mas se  tiver alguem para auxiliar, então, tenho uma tabela oficina e uma usuario, uma oficina pode ter varios usuarios e um usuario estar em varias oficinas. Pensei em criar uma nova tabela para relacionar esses caras

estou testanto aqui, mas qual vcs recomendam usar: has_many :through ou has_and_belongs_to_many?

minha regra nao permite cadastrar um usuario duas vezes na mesma oficina

**Comment by dehvmartins** [comment]
@DenysonDomingos eu costumo usar o `has_many :through` quando vou usar a tabela intermediária para outra coisa além dessa relação. Não sei se você entendeu bem o conceito desses relacionamentos mas nos dois casos existe uma tabela intermediária. A leitura do guides para mim é um bom começo http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by filipebarcos** [comment]
o `has_and_belongs_to_many` é quando vc tem uma relação many to many e a table intermediária só serve para ligar as entidades. Ele é implementado, no rails, por baixo dos panos, com `has_many :through`.

O `has_many :though` tem várias outras utilidades ao meu ver. Por exemplo, quando vc tem `alunos` que pode estar em vários `cursos`, que tem várias `disciplinas`. No meu model aluno, e posso ter o seguinte:

``` ruby
class Aluno < AR::Base
  has_many :cursos
  has_many :disciplinas, through: :cursos
end
```

vc não precisar ir na mão fazer essa query, o Rails te ajuda, e eu posso chamar direto `aluno.disciplinas`, ele já faz o join pra vc 👍
